### PR TITLE
Enable compilation across all platforms

### PR DESCRIPTION
**Pull request by josephwoodward**
Also add Rider to git ignore.

A few tests currently fail when running on a Mac so I'll take a look at them at some point.

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Could you provide details on why it's better to include `Microsoft.NETFramework.ReferenceAssemblies` in the `NLog.StructuredLogging.Json.csproj` file, when it builds without it present; and if it's safe to ship a release using `Version="1.0.0-preview.1` of this package

**Comment by slang25** [comment]
Just to comment on if a preview of ReferenceAssemblies is safe, I would say for most cases yes because the assemblies aren't in preview, the package is, so that means that you won't get weird runtime errors due to compiling against the wrong API surface, it will be either the build works or it fails due to things like filename casing, or some MSBuild problem that mean they don't resolve altogether.

It currently builds in CI ~~as it is finding the mono reference assemblies~~ the build script only builds for `netcoreapp2.1`, this change means that you don't need anything other than the .NET Core SDK to build all tfms.

**Comment by AnthonySteele** [comment]
So this is purely a build-time thing? No impact on the shipped package - I don't want to ship a release with a dependency on a `-preview.1 ` .

**Comment by slang25** [comment]
The `PrivateAssets="All"` part ensures that this package does not end up becoming an external dependency for the project/package.

**Pull request merged**
