### PR TITLE
Try to embed source files

### PR DESCRIPTION
**Pull request by AnthonySteele**
Try to embed source files in .pdbs to help debugging
Like here https://github.com/slang25/JustSaying/commit/47881268d8b1b66ef1bf34399307ac37ba7c9631
as per https://github.com/ctaggart/SourceLink

### CODE REVIEW

**Comment by slang25** [comment]
Looks good. I also tidied up the versioning logic in JustSaying as the AssemblyVersion logic was a bit overkill and not really the done thing. [See here](https://github.com/slang25/JustSaying/commit/2e365594773bc941c5493ca52dab3fefc7a49f34)

**Comment by martincostello** [comment]
What he said.

**Comment by AnthonySteele** [comment]
I think it's worth looking at version numbers separately (and hopefully soon), when the beta suffix falls away.

**Comment by AnthonySteele** [comment]
Hm, I still don't see any `.pdb` files in the `.nupkg`  here https://ci.appveyor.com/project/justeattech/nlog-structuredlogging-json/build/artifacts
Not sure why not  :(

**Comment by snakefoot** [comment]
@AnthonySteele You need `--include-symbols` to get pdb-files.

**Comment by AnthonySteele** [comment]
So the `--include-symbols` produces a separate `.symbols.nupkg` file, which we were looking at doing without.

**Pull request closed without merging**
