### PR TITLE
Netstandard 2

### PR DESCRIPTION
**Pull request by AnthonySteele**
it looks like supporting Netstandard2.0 is the way forward for us:
https://twitter.com/NLogOfficial/status/916053706688401409

### CODE REVIEW

**Comment by martincostello** [comment]
Seems legit. Will ✔️ when/if the builds go green.

**Comment by AnthonySteele** [comment]
I don't think this project needs `AssemblyVersion.cs` as it wasn't there before, just added to keep the new scripts happy.
The `OpenCover` tool was also a new option, but I kept it as it seems useful and simple at first glance.

**Comment by martincostello** [comment]
`AssemblyVersion.cs` is used to patch the assembly with some `[AssemblyMetdata]` attributes that contain the name of the Git branch and SHA.

**Comment by AnthonySteele** [comment]
This builds, but I want to clean it up before merge. Not just squash the history, but  decide if we want that `AssemblyVersion.cs` and the code coverage tool. That might be out of scope for a PR to just get it onto NetStandard 2.0

**Pull request closed without merging**
