### PR TITLE
Update the Newtonsoft.Json version to 10.0.3

### PR DESCRIPTION
**Pull request by AnthonySteele**

### CODE REVIEW

**Comment by slang25** [comment]
Not sure if this PR is from the bot you were talking about building @AnthonySteele ?

**Comment by AnthonySteele** [comment]
I haven't built the bot yet. So far, I'm the bot  :/

**Comment by slang25** [comment]
Hmmm, well it passes the turing test!

**Comment by AnthonySteele** [comment]
When i build this bot, it will claim to be a bot.

**Pull request merged**
